apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lp2u
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0030-tenant/tkrw-pr712-0075-0030-app/devfile-sample-lp2u@sha256:b645c3dff6647463c3e422398deff10f22a00f72b8ead63351889e78fc63a0c0
        name: my-nodejs
        resources: {}
status: {}
